ConsensusCore python build: numpy include path should precede python include path on compile line
(If you have an old numpy installed globally on your machine
and a newer one in your virtualenv, you would get errors like
this on importing the ConsensusCore module:

RuntimeError: module compiled against API version 9 but this version of numpy is 7

This would happen because the build would pick up numpy
headers installed globally, ahead of those found in the
virtualenv.  This change fixes the problem---though internally
we have moved to expunge the global numpy installation.)

[Tracking bug 24842]

[git-p4: depot-paths = "//depot/software/smrtanalysis/bioinformatics/lib/cpp/ConsensusCore/": change = 148527]